version: '3'

services:

  spring-boot-jpa-app:
    image: spring-boot:api
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot


  db:
    image: postgres:9.6
    restart: always

    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: animal
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1234
    volumes:
      - /data/postgres
